name: auth_repo
description: A Flutter package for managing authentication domain.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_auth: ^4.15.2
  firebase_core: ^2.24.2
  google_sign_in: ^6.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  import_sorter: ^4.6.0
  mockito: ^5.4.3
  very_good_analysis: ^5.1.0

import_sorter:
  emojis: false
  comments: false