name: auth_repo
description: A Flutter package for managing authentication domain.
version: 1.0.1+2
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_auth: ^4.17.0
  firebase_core: ^2.25.0
  google_sign_in: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.8
  import_sorter: ^4.6.0
  mockito: ^5.4.4
  very_good_analysis: ^5.1.0

import_sorter:
  emojis: false
  comments: false
